export default function Disclaimer({ text }: { text?: string }) {
  return (
    <p className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2.5 text-[11px] leading-relaxed text-amber-800">
      {text ??
        "Decision-support only. This is a ranked list of possibilities generated by an AI model, not a diagnosis. A licensed physician must review and confirm everything before any clinical action. Not a cleared medical device."}
    </p>
  );
}
